### ISSUE TITLE
Homework Complete

### ISSUE THREAD

**Issue by ray-mroch** [ray-mroch/Mroch-Homework#1]
Homework complete and uploaded.

**Comment by fitzLab-AL** [comment]
Received - thanks. I recommend that you either (1) rename your repository / R-project folder or create a new one and copy your HW1 script over and delete this one. You want *one* repository / R-project folder for the entire class, not one per assignment. 

Thanks.

**Comment by fitzLab-AL** [comment]
Nice work on this.

Grade: 10/10
