### ISSUE TITLE
Homework 2 Complete

### ISSUE THREAD

**Issue by ray-mroch** [ray-mroch/Mroch-Homework#2]
homework 2 is complete and uploaded. I renamed the drive, let me know if I missed the mark and I will correct it.

**Comment by fitzLab-AL** [comment]
Got it - thanks!

**Comment by fitzLab-AL** [comment]
Nice work on this @ray-mroch  - just a few minor issues, see my comments on your .Rmd. Your code worked well, but there were a few areas where a more efficient / less cumbersome approach would have worked. Let me know if you have any questions.

GRADE: 9.5/10

**Comment by ray-mroch** [comment]
OK, thanks for the feedback. I'll review and let you know if I have
questions.

Thanks again,

Ray
